#!/bin/bash
### copy dates lxde clock lxpanel panel ###

get_environnement_graphic() {
    if [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
        echo "Wayland"
        return
    fi
    
    if [[ -n "$DISPLAY" ]]; then
        echo "X11"
        return
    fi

    echo "TTY"
}

get_date() {
    local ENV
    ENV=$(get_environnement_graphic)
    
    local SELECTED_DATE=""
    local ZENITY_RESULT_CODE=0
    
    if [[ "$ENV" == "X11" || "$ENV" == "Wayland" ]]; then
        if ! command -v zenity &> /dev/null; then
            echo "ERREUR: Zenity est introuvable. Impossible d'ouvrir le calendrier." >&2
            ZENITY_RESULT_CODE=1
        else
            SELECTED_DATE=$(zenity --calendar --text "Selectionner une date" --date-format "%Y-%m-%d" 2>/dev/null)
            ZENITY_RESULT_CODE=$?
        fi
    else
        echo "TTY detecte. bypasse Zenity." >&2
    fi
    
    if [[ -z "${SELECTED_DATE}" || "$ZENITY_RESULT_CODE" -ne 0 ]]; then 
        SELECTED_DATE=$(date +"%Y-%m-%d")
        
        if [[ "$ENV" != "TTY" ]]; then
            echo "Pas selection, la date du jour utilisee." >&2
        else
            echo "Date retenue: ${SELECTED_DATE}" >&2
        fi
        
    fi
    
    echo "${SELECTED_DATE}"
    return 0
}


selectDate() {
    local ENV
    ENV=$(get_environnement_graphic)
    SCRIPT_PATH=$(realpath "$0" 2>/dev/null || echo "$0")
    local FINAL_DATE
    FINAL_DATE=$(get_date)
    local EXIT_CODE=0

    case "$ENV" in
        "TTY")
            echo "\$DATE sera utilisable si le script est lance avec la commande:">&2
            echo "">&2
            echo "   source $SCRIPT_PATH">&2
            echo "">&2            
            ;;

        "Wayland")
            if command -v wl-copy &> /dev/null; then
                wl-copy "$FINAL_DATE"
            else
                zenity --error --text="Wayland detecte, mais 'wl-copy' est introuvable. Veuillez installer 'wl-clipboard'."
                EXIT_CODE=1
            fi
            ;;

        "X11")
            if command -v xclip &> /dev/null; then
                echo "$FINAL_DATE" | xclip -selection clipboard -i
            else
                zenity --error --text="X11 detecte, mais 'xclip' est introuvable. Veuillez installer 'xclip'."
                EXIT_CODE=1
            fi
            ;;
        
        *)
            zenity --error --text="Environnement inconnu ($ENV). La date du jour ($FINAL_DATE) est utilisee."
            echo "ATTENTION: Environnement inconnu ($ENV). La date du jour ($FINAL_DATE) est utilisee." >&2
            ;;
    esac

    if [ "$EXIT_CODE" -ne 0 ]; then
        exit 1
    fi
    
    echo "$FINAL_DATE"
}

# capture le dernier 'echo' de la fonction dans la variable DATE_POUR_LE_SCRIPT
DATE=$(selectDate)

echo "--- EXEMPLES D'UTILISATION ---"
echo "Par exemple : mkdir -p \$DATE (mkdir -p $DATE)"
echo "créer un fichier : touch \$DATE.txt (touch $DATE)"
